packages:
  - "apps/*"
  - "packages/*"

overrides:
  metro: "0.83.7"
  metro-babel-transformer: "0.83.7"
  metro-cache: "0.83.7"
  metro-cache-key: "0.83.7"
  metro-config: "0.83.7"
  metro-core: "0.83.7"
  metro-file-map: "0.83.7"
  metro-minify-terser: "0.83.7"
  metro-resolver: "0.83.7"
  metro-runtime: "0.83.7"
  metro-source-map: "0.83.7"
  metro-symbolicate: "0.83.7"
  metro-transform-plugins: "0.83.7"
  metro-transform-worker: "0.83.7"
